live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[shell] 
program = "/bin/zsh"
args = ["-c", "launch-or-attach-tmux"]

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty"
opacity = 0.95
decorations_theme_variant = "Dark"
padding = { x = 15, y = 15 }

[window.dimensions]
#columns = 100
#lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

#[colors.primary]
#background = '#282C34'
#foreground = '#DFDFDF'

#[colors.normal]
#black = '#1B2229'
#blue = '#51AFEF'
#cyan = '#46D9FF'
#green = '#98BE65'
#magenta = '#C678DD'
#red = '#FF6C6B'
#white = '#DFDFDF'
#yellow = '#ECBE7B'
#
#[colors.bright]
#black = '#73797E'
#blue = '#51AFEF'
#cyan = '#46D9FF'
#green = '#98BE65'
#magenta = '#C678DD'
#red = '#FF6C6B'
#white = '#DFDFDF'
#yellow = '#ECBE7B'
#
#[colors.selection]
#background = '#2257A0'
#foreground = '#DFDFDF'

[colors.primary]
background = '#1F1F28'
foreground = '#DCD7BA'

[colors.normal]
black = '#16161D'
blue = '#7E9CD8'
cyan = '#7FB4CA'
green = '#98BB6C'
magenta = '#957FB8'
red = '#E82424'
white = '#DCD7BA'
yellow = '#E6C384'

[colors.bright]
black = '#727169'
blue = '#7E9CD8'
cyan = '#7FB4CA'
green = '#98BB6C'
magenta = '#957FB8'
red = '#E82424'
white = '#DCD7BA'
yellow = '#E6C384'

[colors.selection]
background = '#223249'
foreground = '#DCD7BA'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

[font]
size = 12
offset.y = 0

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Regular"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "0xProto Nerd Font Mono"
style = "Regular Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15
blink_interval = 500

[cursor.style]
shape = "Block" 
blinking = "Always"

[mouse]
hide_when_typing = true
