#!/bin/bash

export MANGOHUD_CONFIGFILE="$hypr/mangohud/DD2.conf"
#export DXVK_HDR=1
#export ENABLE_HDR_WSI=1
#export VKD3D_FEATURE_LEVEL=12_2 
#export VKD3D_SHADER_MODEL=6_6 
#export RADV_PERFTEST=nosam
#export VKD3D_SHADER_CACHE_PATH=0
#export VKD3D_CONFIG=no_upload_hvv
#export WINEDLLOVERRIDES="dinput8=n,b"

#AMD_VLK="$(which vk_amdvlk)"

#exec $AMD_VLK\
     "$@"
