#!/bin/bash

SCRIPT_HOME="$(dirname $(realpath "$0"))"
STEAMAPPS_JSON="$SCRIPT_HOME/steamapps.json"
COMPAT_STEAM_DIRS=$(find $HOME -iwholename "*steamapps/compatdata")

if [ "$1" = 'update' ]; then
    curl https://api.steampowered.com/ISteamApps/GetAppList/v2/ -o $STEAMAPPS_JSON     
    exit
fi


if [ "$1" = 'game-name' ]; then
    echo $(jq "[.applist.apps[] | select(.appid == $2)][0]" $STEAMAPPS_JSON | jq -r '.name')
    exit
fi

patch_game_name() {
    case $1 in
        "CHRONO CROSS: THE RADICAL DREAMERS EDITION")
	    echo "CHRONO CROSS  THE RADICAL DREAMERS EDITION"
	;;

        "Remnant II")
	    echo "Remnant2"
	;;

	"MONSTER HUNTER RISE")
	    echo "MonsterHunterRise"
        ;;

	"Wo Long: Fallen Dynasty")
	    echo "WoLongFallenDynasty"
        ;;

        "CRISIS CORE –FINAL FANTASY VII– REUNION")
	    echo "CCFF7R"
        ;;

        "Dragon's Dogma 2")
	    echo "Dragons Dogma 2"
        ;;

	"FINAL FANTASY X/X-2 HD Remaster")
	    echo "FINAL FANTASY FFX&FFX-2 HD Remaster"
        ;;

	"Divinity: Original Sin 2")
	    echo "Divinity Original Sin 2"
        ;;

	"Granblue Fantasy: Relink")
	    echo "Granblue Fantasy Relink"
        ;;

	*)
	    echo "$1"
	;;

    esac
}

if [ "$1" = 'missing-folders' ]; then
    for COMPAT_STEAM_DIR in $COMPAT_STEAM_DIRS
    do
        APP_IDS=$(ls $COMPAT_STEAM_DIR | xargs)
        OLD_IFS=$IFS

        IFS=" "
        for APP_ID in $APP_IDS
        do
            if ! [ "$APP_ID" = "0" ]; then
                GAME_NAME=$(jq "[.applist.apps[] | select(.appid == $APP_ID)][0]" $STEAMAPPS_JSON | jq -r '.name')
                if ! [ "$GAME_NAME" = "" ] && ! [ "$GAME_NAME" = "null" ]; then
		    FOLDER_NAME=$(patch_game_name "$GAME_NAME")
                    GAME_DIR="$COMPAT_STEAM_DIR/../common/$FOLDER_NAME"
                    if ! [ -d "$GAME_DIR" ]; then
            	        echo "\"$GAME_NAME\""
                    fi
                fi
            fi
        done
        IFS=$OLD_IFS
    done
    exit
fi

for COMPAT_STEAM_DIR in $COMPAT_STEAM_DIRS
do
    APP_IDS=$(ls $COMPAT_STEAM_DIR | xargs)
    OLD_IFS=$IFS

    IFS=" "
    for APP_ID in $APP_IDS
    do
	if ! [ "$APP_ID" = "0" ]; then
	    GAME_NAME=$(jq "[.applist.apps[] | select(.appid == $APP_ID)][0]" $STEAMAPPS_JSON | jq -r '.name')
	    if ! [ "$GAME_NAME" = "" ] && ! [ "$GAME_NAME" = "null" ]; then
		    FOLDER_NAME=$(patch_game_name "$GAME_NAME")
	        GAME_DIR="$COMPAT_STEAM_DIR/../common/$FOLDER_NAME"
	        if [ -d "$GAME_DIR" ]; then
		        REALPATH_GAME=$(realpath "$GAME_DIR")
		        rm "$REALPATH_GAME/WINE_PREFIX"
	            ln -s "$COMPAT_STEAM_DIR/$APP_ID" "$REALPATH_GAME/WINE_PREFIX"
		        echo "Establishing soft link to prefix in: $REALPATH_GAME/WINE_PREFIX"
                continue
            fi
		    echo "Could not find folder for game: $GAME_NAME"
	    fi
	fi
    done
    IFS=$OLD_IFS
done

