#!/bin/bash

PROMPT="Master Password:"
PIDS=$(pidof rofi)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

export MASTER_PASSWORD=$(rofi -p "$PROMPT" -dmenu -password)
export BW_SESSION=$(bw unlock --passwordenv "MASTER_PASSWORD" --raw)

send_notification() {
    notify-send -u "low" -a "Bitwarden CLI" -i "bitwarden" -c "Bitwarden CLI" "Bitwarden CLI" "$1"
}

if [[ -z "$BW_SESSION" ]]; then
    send_notification "Wrong master password!"
    exit
fi

trap "bw lock; exit" SIGINT EXIT ERR

BT_ITEMS=$(bw list items | jq 'map({ id: .id, name: .name, pass: .login.password })')
OPTS=$(echo "$BT_ITEMS" | jq -r '.[] | .name')

SELECTED_NAME=$(echo "$OPTS" | rofi -dmenu -i -p "$PROMPT")
SELECTED_PASS=$(echo "$BT_ITEMS" | jq -r --arg SN "$SELECTED_NAME" '.[] | select(.name == $SN) | .pass')

if [[ ! -z "$SELECTED_PASS" ]]; then
    wl-copy "$SELECTED_PASS"
    send_notification "$SELECTED_NAME password copied!"
fi
