#!/bin/bash

trap "hyprctl hyprpaper unload all" SIGINT ERR EXIT
source $(which set-hyprland-socket)

set_wallpaper() {
    if [ ! -z "$1" ]; then    
        SELECTED=$(echo -e $WALLPAPER_LIST | grep "$1")
        hyprctl hyprpaper preload "$SELECTED"

        MONITORS=$(hyprctl monitors -j | jq '[.[]]|sort_by(.name)' | jq -r '.[].name')
        OUTPUT="splash = false\n\npreload = $SELECTED\n"

        for monitor in $MONITORS; do
           OUTPUT="$OUTPUT\nwallpaper = $monitor,$SELECTED" 
           hyprctl hyprpaper wallpaper "$monitor,$SELECTED"
        done

        echo -e $OUTPUT > $hypr/hyprpaper.conf 

        sed "s|path\ \=\ .*|path\ \=\ $SELECTED|g" "$hypr/hyprlock.proto.conf" > "$hypr/hyprlock.conf"
    fi
}

if [[ ! -z "$1" ]] && [[ -f "$1" ]]; then
    MIME_TYPE=$(file -Lb --mime-type "$1")

    if [[ "$MIME_TYPE" =~ ^image\/ ]]; then
        WALLPAPER_LIST="$1"
        set_wallpaper "$1"
    fi
    exit
fi

PROMPT="Wallpaper:"
PIDS=$(pidof rofi)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

add_wallpaper_from_folder() {
    SAVEIFS="$IFS"
    IFS=$(echo -en "\n\b")
    FILES=$(ls "$1")
    for f in ${FILES[@]}; do
        [ -d "$1/$f" ] && add_wallpaper_from_folder "$1/$f" || add_wallpaper "$1/$f"
    done
    IFS="$SAVEIFS"
}

add_wallpaper() {
    if [ -f "$1" ]; then
        MIME_TYPE=$(file -Lb --mime-type "$1")
        if [[ $MIME_TYPE =~ ^image\/ ]]; then
            WALLPAPER_LIST=$([ -z "$WALLPAPERS" ] && echo $1 || echo "$WALLPAPER_LIST\n$1")
        fi
    fi
}

WALLPAPER_FOLDERS=""

add_wallpaper_folder() {
    WALLPAPER_FOLDERS=$([ -z "$WALLPAPER_FOLDERS" ] && echo "$1" || echo "$WALLPAPER_FOLDERS:$1")
}

remove_wallpaper_folder() {
    if [ ! -z "$WALLPAPER_FOLDERS" ]; then
        FOLDER_NAME=$(echo "$1" | cut -d '!' -f2-)
        WALLPAPER_FOLDERS=$(echo "$WALLPAPER_FOLDERS" | sed "s|$FOLDER_NAME||" | sed "s|::|:|")

        if [ $(echo "$WALLPAPER_FOLDERS" | cut -c1) == ":" ]; then
            WALLPAPER_FOLDERS=$(echo "$WALLPAPER_FOLDERS" | cut -d ':' -f2-)
        fi
    fi
}

add_wallpaper_folder "$HOME/.local/share/wallpapers"
add_wallpaper_folder "/usr/share/wallpapers"

for extraInArguments in "$@"; do
    add_wallpaper_folder "$extraInArguments"
done

while read extraInFile; do
    extraInFile=$(echo "$extraInFile" | envsubst)
    trimmed=$(echo "$extraInFile" | xargs -0)
    firstChar=$(echo "$trimmed" | cut -c1)

    if [ "$firstChar" == "#" ]; then
        continue
    fi

    if [ "$firstChar" == "!" ]; then
        remove_wallpaper_folder "$extraInFile"
        continue
    fi

    add_wallpaper_folder "$extraInFile"
done < "$hypr/wallpaper_folders.config.txt"

WALLPAPER_LIST=""

OLDIFS="$IFS"
IFS=":" read -ra WALLPAPERS <<< "$WALLPAPER_FOLDERS"
for wallpaper in "${WALLPAPERS[@]}"; do
    add_wallpaper_from_folder "$wallpaper"
done
IFS="$OLDIFS"

WALLPAPER_OPTS=$(echo -e "$WALLPAPER_LIST" | grep -v "^$" | map basename)
SELECTED_FILE=$(echo "$WALLPAPER_OPTS" | rofi -application-fallback-icon "application-x-addon" -dmenu  -i -p "$PROMPT")

set_wallpaper "$SELECTED_FILE"
