#!/bin/bash

MANGO_FOLDER="$hypr/MangoHud"
MANGO_FILE="$MANGO_FOLDER/MangoHud.conf"
AVAILABLE_CONFS=$(find "$MANGO_FOLDER" -iname "*.proto.conf")
SELECTED=$(echo "$AVAILABLE_CONFS" | map basename | cut -d '.' -f1 | rofi -dmenu)

if [[ ! -z "$SELECTED" ]]; then
    ln -sfT "$(echo "$AVAILABLE_CONFS" | grep "$SELECTED.proto.conf" | head -n 1)" "$MANGO_FILE"
fi
