#!/bin/bash

source $(which set-hyprland-socket)

add_wallpaper_from_folder() {
    SAVEIFS="$IFS"
    IFS=$(echo -en "\n\b")
    FILES=$(ls "$1")
    for f in ${FILES[@]}; do
        [ -d "$1/$f" ] && add_wallpaper_from_folder "$1/$f" || add_wallpaper "$1/$f"
    done
    IFS="$SAVEIFS"
}

add_wallpaper() {
    if [ -f "$1" ]; then
        EXTENSION=$(echo $(basename "$1") | cut -d '.' -f 2)
        if [ $EXTENSION == "png" ] || [ $EXTENSION == "jpg" ]; then
            WALLPAPER_LIST=$([ -z "$WALLPAPERS" ] && echo $1 || echo "$WALLPAPER_LIST\n$1")
        fi
    fi
}

WALLPAPER_FOLDERS=""

add_wallpaper_folder() {
    WALLPAPER_FOLDERS=$([ -z "$WALLPAPER_FOLDERS" ] && echo "$1" || echo "$WALLPAPER_FOLDERS:$1")
}

add_wallpaper_folder "$HOME/.local/share/wallpapers"
add_wallpaper_folder "/usr/share/wallpapers"

for extraInArguments in "$@"; do
    add_wallpaper_folder "$extraInArguments"
done

EXTRA_FROM_FILE=$(cat "$hypr/extra_wallpaper_folders.txt")

for extraInFile in "$EXTRA_FROM_FILE"; do
    add_wallpaper_folder "$extraInFile"
done

WALLPAPER_LIST=""

OLDIFS="$IFS"
IFS=":" read -ra WALLPAPERS <<< "$WALLPAPER_FOLDERS"
for wallpaper in "${WALLPAPERS[@]}"; do
    add_wallpaper_from_folder "$wallpaper"
done
IFS="$OLDIFS"

WALLPAPER_OPTS=$(echo -e "$WALLPAPER_LIST" | map basename)
SELECTED_FILE=$(echo "$WALLPAPER_OPTS" | tofi --prompt-text="Choose Wallpaper:" -c $hypr/tofi/config)

if [ ! -z "$SELECTED_FILE" ]; then
    SELECTED=$(echo -e $WALLPAPER_LIST | grep "$SELECTED_FILE")

    MONITORS=$(hyprctl monitors -j | jq '[.[]]|sort_by(.name)' | jq -r '.[].name')
    OUTPUT="splash = false\n\npreload = $SELECTED\n"

    for monitor in $MONITORS; do
       OUTPUT="$OUTPUT\nwallpaper = $monitor,$SELECTED" 
    done

    echo -e $OUTPUT > $hypr/hyprpaper.conf
fi


