#!/bin/bash

PROMPT="Kill:"
PIDS=$(pidof rofi)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

TARGET=$(ps ax -o pid,cmd | tail -n +2 | rofi -dmenu -i -p "$PROMPT")

if [ ! -z "$TARGET" ]; then
    PID=$(echo "$TARGET" | cut -d ' ' -f 2)
    kill -9 $PID
fi

