#!/bin/bash

PROMPT="Kill:"
PIDS=$(pidof rofi)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

PROCS=$(ps -o pid,cmd -u "$USER" | tail -n +2)
ENTRIES=""

while read proc; do
    PS_PID=$(echo "$proc" | cut -d ' ' -f1) 
    PS_CMD=$(echo "$proc" | cut -d ' ' -f2-) 

    ENTRIES="$ENTRIES$PS_PID | $(echo "$PS_CMD" | awk '{print substr($0,0,20)" ... "substr($0,length($0)-29,30)}')\n"
done <<< "$PROCS"

TARGET=$(echo -e "$ENTRIES" | rofi -dmenu -i -p "$PROMPT")

if [ ! -z "$TARGET" ]; then
    kill -9 $(echo "$TARGET" | cut -d ' ' -f1)
fi

