#!/bin/bash

PROMPT="Kill:"
PIDS=$(find-pid-bytitleclass "wofi" "$PROMPT" | xargs)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

TARGET=$(ps ax -o pid,cmd | tail -n +2 | wofi --dmenu -i --prompt "$PROMPT" --width="60%" --height="50%")

if [ ! -z "$TARGET" ]; then
    PID=$(echo "$TARGET" | cut -d ' ' -f 2)
    kill -9 $PID
fi

