#!/bin/bash

if [ "$1" == "gui" ]; then
    VISUAL=$([ ! -z "$VISUAL" ] && echo "$VISUAL" || echo "neovide")
    "$VISUAL" "$hypr"
    exit 0
fi

EDITOR=$([ ! -z "$EDITOR" ] && echo "$EDITOR" || echo "nvim")

"$EDITOR" -c "e $hypr"
