#!/bin/bash

UPDATES=$(checkupdates --nocolor)
COUNT_UPDATES=0

OLDIFS="$IFS"
IFS=$(echo -en "\n\b")
UPDATE_STRING=""

for update in ${UPDATES[@]}; do
    UPDATE_STRING=$([ -z $UPDATE_STRING ] && echo "$update" || "$UPDATE_STRING\n$update")
    COUNT_UPDATES=$(bc <<< "$COUNT_UPDATES+1")
done

IFS="$OLDIFS"

echo "{ \"text\": \"$COUNT_UPDATES\", \"tooltip\": \"$UPDATE_STRING\"}"
