#!/bin/bash

PROMPT="Action:"
PIDS=$(find-pid-bytitleclass "wofi" "$PROMPT" | xargs)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

entries="Lock\nLogout\nSuspend\nReboot\nShutdown"

selected=$(echo -e $entries | wofi --dmenu -i --width="350px" --height="290px" --prompt "$PROMPT" | awk '{print tolower($2)}')

case $selected in
  lock)
	  lock-system;;
  logout)
    hyprctl dispatch exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
