#!/bin/bash

PROMPT="Action:"
PIDS=$(pidof rofi)

[[ ! -z $PIDS ]] && kill -9 $PIDS && exit

entries="󰌾 Lock\n⇠   Logout\n⏾ Suspend\n󰑓 Reboot\n⏻ Shutdown"

selected=$(echo -e $entries | rofi -dmenu -i -p "$PROMPT" | awk '{print tolower($2)}')

case $selected in
  lock)
	  lock-system;;
  logout)
    hyprctl dispatch exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
