#!/bin/bash

GPU_PCT=$(cat /sys/class/hwmon/hwmon4/device/gpu_busy_percent)
#GPU_CLK_RAW=$(cat /sys/class/hwmon/hwmon4/freq1_input)

#GPU_CLK_MHZ=$(expr $GPU_CLK_RAW / 1000000)

#echo "<big>󰡁</big> $(bc <<< "scale=2;$GPU_CLK_MHZ/1000" | sed 's/^\./0./')Ghz <span color=\"darkgray\">| $GPU_PCT%</span>"

echo "<big>󰡁</big><span color=\"darkgray\"> $GPU_PCT%</span>"
