#!/bin/bash

SOURCE=$(realpath "$1")

if [ -f "$SOURCE" ] || [ -d "$SOURCE" ]; then
    echo -n "Enter new name [$(basename "$SOURCE")]: " && read NEW_NAME 

    if [[ ! -z $NEW_NAME ]]; then
        mv "$SOURCE" "$(dirname "$SOURCE")/$NEW_NAME"
        exit 0
    fi

    echo "Invalid new name!"
    exit 2  
fi

echo "File not found!"
exit 1

