#!/bin/bash

SCRIPTS_DIR="$hypr/scripts"

SELECTED="$(command find $SCRIPTS_DIR | \
	prune-dirs | \
	map basename | \
	cut -d'.' -f1 | \
	rofi -dmenu -i -p "Pick a Script:")"

if [[ -n $SELECTED ]]; then
	ACTION=$(echo -e "Run\nEdit\nMake Executable\nCreate Link" | rofi -dmenu -p "Choose an Action:")

	SCRIPT_REAL_PATH=$(find "$SCRIPTS_DIR" -wholename "*/$SELECTED")

    echo "$SCRIPT_REAL_PATH"

    case "$ACTION" in
        Run) exec "$SCRIPT_REAL_PATH";;
        Edit) exec "$TERMINAL" --class "script-editor" "$EDITOR" "$SCRIPT_REAL_PATH";;
        Make\ Executable) exec chmod +x "$SCRIPT_REAL_PATH";;
        Create\ Link) sudo ln -fs "$SCRIPT_REAL_PATH" "/usr/bin/$SELECTED";;
        *) exit
    esac	
fi

