#!/bin/bash

CONFIG="$hypr/waybar/config-hypr.jsonc"
STYLE="$hypr/waybar/style.css"
MODULES="$hypr/waybar/modules"

CONFIG_FILES="$CONFIG $STYLE $MODULES"

trap "killall waybar; exit" EXIT SIGINT

while true; do
    waybar --log-level error --config ${CONFIG} --style ${STYLE} &
    sleep 10 
    update-waybar 8 
    update-waybar 9
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
